In [1]:
#Exp_No:5

In [3]:
#Aim:To Create 1D,2D and Multidimensional Array

In [4]:
#Name:Mohini Rajesh Ganjare
#Roll no:16
#Sec:B
#Sub:ET1
#Date:21/08/2025

In [5]:
#importing the basic library
import numpy as np

In [6]:
#Creating 1D Array using numpy

In [11]:
a1=np.array([10,20,30,40,50])

In [12]:
a1

array([10, 20, 30, 40, 50])

In [13]:
a2=np.array([[10,20,30,40],[50,60,70,80]])

In [14]:
a2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [15]:
#Creating 2D Array using numpy

In [16]:
a3=np.matrix('10 20;30 40;50 60')

In [17]:
a3

matrix([[10, 20],
        [30, 40],
        [50, 60]])

In [22]:
#Creating Array Of 10 Random Intergers Between 10 to 15
arr=np.random.randint(10,15,size=10)
print(arr)

[13 14 12 14 10 10 14 10 12 12]
